jobs:
  - script: >
      pipelineJob('maven-pipeline-version-controlled') {
          definition {
            triggers {
                cron('H/5 * * * *') ###this is will trigger this job 5 mins after the jenkins build finished
            }
            cpsScm {
                scm {
                  git {
                      remote { url 'https://github.com/tsundberg/maven-build-with-jenkins-pipeline.git'}
                      branch '*/master'
                      extensions {}    
                  }
                }
                scriptPath 'src/ci/Jenkinsfile'
            }
          }
      }
